### ISSUE TITLE
不能正常mount sa及comfig.js至gd-utils

### ISSUE THREAD

**Issue by karickkl** [gdtool/gd-utils-docker#5]
不能正常mount sa及comfig.js至gd-utils，文件已被mount到/root/gd-utils，但docker啟動時沒有自動把文件載入到/gd-utils

手動複製 sa account 至gd-utils後，telegram bot也顯示沒有sa account 可用

**Comment by gdtool** [comment]
文件在docker内的绝对路径是/gd-utils

**Comment by karickkl** [comment]
我嘗試把 /root/gd-utils/sa 複製到 /gd-utils/sa，但telegram bot還是顯示沒有sa account 可用

**Comment by karickkl** [comment]
能提供docker-compose.yml 的編寫方法嗎? 謝謝 @gdtool
