### ISSUE TITLE
gdtool/gd-utils-docker 无法使用

### ISSUE THREAD

**Issue by lxmicode** [gdtool/gd-utils-docker#6]
gd-utils    | passwd: password for root changed by root
gd-utils    | passwd: password for gd changed by root
gd-utils    | /start.sh: line 9: /gd-utils/sa/shellinaboxd: No such file or directory
gd-utils exited with code 127
gd-utils    | passwd: password for gd changed by root
gd-utils    | /start.sh: line 9: /gd-utils/sa/shellinaboxd: No such file or directory
gd-utils exited with code 127

只能clone 项目从头编译使用吗

**Comment by psychopasss** [comment]
+1

**Comment by We1eVen** [comment]
作者教程不太详细。
docker的目录映射关系是从主机到容器，也就是说在映射的主机目录会覆盖映射的容器目录，而主机目录为空，因此容器的gd-utils目录内文件直接被抹除了，所以会报错 /gd-utils/sa/shellinaboxd: No such file or directory
解决方法有二:
1.目录映射参数改为 -v /gd-utils:/home/gd
然后将sa文件放入主机的/gd-utils目录下（主机目录也可自行修改），接下来进入容器自带的webshell,将sa文件拷贝至sa目录下，命令为: cp *.json /gd-utils/sa
然后修改容器/gd-utils目录下config.js文件并重启容器就可以正常使用了。
2.将容器中的/gd-utils目录下所有文件拷贝至主机的映射目录/gd-utils中，这样就可以正常使用参数 -v /gd-utils:/gd-utils

**Comment by gdtool** [comment]
已经简化，请见使用说明
