### ISSUE TITLE
我用默认的账号gd密码pwd123456 登陆不上

### ISSUE THREAD

**Issue by meichuanyi** [gdtool/gd-utils-docker#7]
请问如何修改密码？

**Comment by gdtool** [comment]
-e USERPWD=pwd123456

**Comment by meichuanyi** [comment]
> -e USERPWD=pwd123456

谢啦大佬，我接下来是想用上gd机器人，但我用的是群晖的docker，想问一下iwestlin/gd-utils 的教程命令执行是在哪？在webshell 还是 ssh

**Comment by gdtool** [comment]
宿主机进入docker内执行
webshell可直接执行
